### PR TITLE
add support for msgpack

### PR DESCRIPTION
**Pull request by scw007**
Hi, I added support for msgpack for a thing I was working on. I got everything I needed out of it with this, so PRing incase anyone else needs it. I would add some tests with a flow file with message pack requests and responses, but I can't get the current set of tests to pass on master in my dev environment.

### CODE REVIEW

**Comment by alufers** [comment]
Hi, how do the tests fail on your machine?

**Comment by alufers** [comment]
The tests failed for this branch because you were parsing responses as msgpack even when they were JSON

**Comment by alufers** [comment]
Same thing with requests

**Comment by alufers** [comment]
I have fixed that problem. Please provide some test data and we can merge it

**Comment by scw007** [comment]
Thanks for the fix. The tests fail on my machine on Windows with mingw, although it could also be a python version issue...

However, it passes on WSL, so I can work on the test next.

This is the output Windows in mingw when I run the tests.
```
$ poetry run pytest
================================================================================================================================= test session starts =================================================================================================================================
platform win32 -- Python 3.12.1, pytest-7.4.3, pluggy-1.3.0
rootdir: C:\Users\steve\dev\mitmproxy2swagger
plugins: asyncio-0.23.2, cov-4.1.0
asyncio: mode=Mode.STRICT
collected 8 items

mitmproxy2swagger\test_mitmproxy2swagger.py .FFF                                                                                                                                                                                                                                 [ 50%]
mitmproxy2swagger\test_openapi_compliance.py ....                                                                                                                                                                                                                                [100%]

====================================================================================================================================== FAILURES =======================================================================================================================================
__________________________________________________________________________________________________________ test_mitmproxy2swagger_generates_swagger_from_mitmproxy_flow_file __________________________________________________________________________________________________________

    def test_mitmproxy2swagger_generates_swagger_from_mitmproxy_flow_file():
        data = mitmproxy2swagger_e2e_test(
            "testdata/test_flows",
            "https://httpbin.org/",
            [
                "--format",
                "flow",
            ],
        )
        assert data is not None
        assert "paths" in data
>       assert len(data["paths"]) == 3  # 4 paths in the test file
E       assert 0 == 3
E        +  where 0 = len({})

mitmproxy2swagger\test_mitmproxy2swagger.py:32: AssertionError
-------------------------------------------------------------------------------------------------------------------------------- Captured stdout call ---------------------------------------------------------------------------------------------------------------------------------
No existing swagger file found. Creating new one.
Flow file corrupted: Invalid data format.
Done!
Flow file corrupted: Invalid data format.
Done!
__________________________________________________________________________________________________ test_mitmproxy2swagger_generates_swagger_from_mitmproxy_flow_file_with_form_data ___________________________________________________________________________________________________

    def test_mitmproxy2swagger_generates_swagger_from_mitmproxy_flow_file_with_form_data():
        data = mitmproxy2swagger_e2e_test(
            "testdata/form_data_flows",
            "https://httpbin.org/",
            [
                "--format",
                "flow",
            ],
        )
        assert data is not None

>       assert (
            get_nested_key(
                data,
                "paths./post.post.requestBody.content.application/x-www-form-urlencoded.schema",
            )
            is not None
        )
E       AssertionError: assert None is not None
E        +  where None = get_nested_key({'openapi': '3.0.0', 'info': {'title': 'testdata/form_data_flows Mitmproxy2Swagger', 'version': '1.0.0'}, 'servers': [{'url': 'https://httpbin.org', 'description': 'The default server'}], 'paths': {}, 'x-path-templates': []}, 'paths./post.post.requestBody.content.application/x-www-form-urlencoded.schema')

mitmproxy2swagger\test_mitmproxy2swagger.py:47: AssertionError
-------------------------------------------------------------------------------------------------------------------------------- Captured stdout call ---------------------------------------------------------------------------------------------------------------------------------
No existing swagger file found. Creating new one.
Flow file corrupted: Invalid data format.
Done!
Flow file corrupted: Invalid data format.
Done!
_______________________________________________________________________________________________________________ test_mitmproxy2swagger_generates_headers_for_flow_files _______________________________________________________________________________________________________________

    def test_mitmproxy2swagger_generates_headers_for_flow_files():
        data = mitmproxy2swagger_e2e_test(
            "testdata/form_data_flows",
            "https://httpbin.org/",
            [
                "--format",
                "flow",
                "--headers",
            ],
        )
        assert data is not None
>       assert (
            get_nested_key(data, "paths./post.post.responses.200.headers.content-type")
            is not None
        )
E       AssertionError: assert None is not None
E        +  where None = get_nested_key({'openapi': '3.0.0', 'info': {'title': 'testdata/form_data_flows Mitmproxy2Swagger', 'version': '1.0.0'}, 'servers': [{'url': 'https://httpbin.org', 'description': 'The default server'}], 'paths': {}, 'x-path-templates': []}, 'paths./post.post.responses.200.headers.content-type')

mitmproxy2swagger\test_mitmproxy2swagger.py:67: AssertionError
-------------------------------------------------------------------------------------------------------------------------------- Captured stdout call ---------------------------------------------------------------------------------------------------------------------------------
No existing swagger file found. Creating new one.
Flow file corrupted: Invalid data format.
Done!
Flow file corrupted: Invalid data format.
Done!
================================================================================================================================== warnings summary ===================================================================================================================================
mitmproxy2swagger/test_openapi_compliance.py::test_mitmproxy2swagger_compliance_from_mitmproxy_flow_file
mitmproxy2swagger/test_openapi_compliance.py::test_mitmproxy2swagger_compliance_from_mitmproxy_flow_file_with_headers
mitmproxy2swagger/test_openapi_compliance.py::test_mitmproxy2swagger_compliance_from_har_file_with_headers
mitmproxy2swagger/test_openapi_compliance.py::test_mitmproxy2swagger_compliance_from_form_data_file_with_headers
  C:\Users\steve\AppData\Local\pypoetry\Cache\virtualenvs\mitmproxy2swagger-3qjgXeeh-py3.12\Lib\site-packages\openapi_spec_validator\shortcuts.py:66: DeprecationWarning: validate_spec shortcut is deprecated. Use validate instead.
    warnings.warn(

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=============================================================================================================================== short test summary info ===============================================================================================================================
FAILED mitmproxy2swagger/test_mitmproxy2swagger.py::test_mitmproxy2swagger_generates_swagger_from_mitmproxy_flow_file - assert 0 == 3
FAILED mitmproxy2swagger/test_mitmproxy2swagger.py::test_mitmproxy2swagger_generates_swagger_from_mitmproxy_flow_file_with_form_data - AssertionError: assert None is not None
FAILED mitmproxy2swagger/test_mitmproxy2swagger.py::test_mitmproxy2swagger_generates_headers_for_flow_files - AssertionError: assert None is not None
======================================================================================================================= 3 failed, 5 passed, 4 warnings in 2.43s =======================================================================================================================

```

**Comment by alufers** [comment]
Weird, I will have to test this on windows

**Comment by scw007** [comment]
thanks!

**Pull request merged**
